//! Spotifast's internals, exposed so diagnostics and tests can reach them.

#[cfg(target_os = "android")]
pub mod android;
pub mod api;
pub mod app;
#[cfg(target_os = "linux")]
pub mod appearance;
pub mod auth;
pub mod autoscroll;
pub mod backend;
pub mod bidi;
pub mod credentials;
#[cfg(any(test, feature = "demo"))]
pub mod demo;
pub mod eq;
pub mod history;
pub mod http;
pub mod i18n;
pub mod images;
pub mod liked;
pub mod limiter;
pub mod link;
pub mod lyrics;
#[cfg(target_os = "macos")]
pub mod mac_links;
#[cfg(target_os = "macos")]
pub mod mac_menu;
#[cfg(target_os = "macos")]
pub mod mac_touchbar_crash_guard;
pub mod media;
#[cfg(target_os = "linux")]
#[path = "mpris.rs"]
pub mod media_controls;
#[cfg(target_os = "android")]
#[path = "media_android.rs"]
pub mod media_controls;
#[cfg(not(any(target_os = "linux", target_os = "android")))]
#[path = "media_native.rs"]
pub mod media_controls;
pub mod milkdrop;
pub mod model;
pub mod opener;
pub mod paths;
pub mod player;
pub mod playlist_cover;
pub mod resample;
pub mod session_reads;
pub mod settings;
pub mod single_instance;
pub mod sink;
pub mod skin;
pub mod system_fonts;
pub mod theme;
pub mod thumbbar;
pub mod ui;
pub mod updates;
pub mod util;
pub mod vis;
pub mod winamp;
pub mod window;
pub mod zeroconf;
